# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://messil.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

subscribe_facebook_url: "http://facebook.com"
subscribe_twitter_url: "http://twitter.com"

google_play_url: "https://play.google.com/store/apps/details?id=com.mdoncall"
appstore_url: "https://itunes.apple.com/ca/app/md-on-call-practical-guide/id333195169"

mailchimp_action_url: "//messil.us8.list-manage.com/subscribe/post?u=610472a7da1d9ffb00b03d491&amp;id=eb93e1513a"
mailchimp_hidden_field_name: "b_610472a7da1d9ffb00b03d491_eb93e1513a"

facebook_share_app_id: "105031042867355"

# Build settings
markdown: kramdown

#output settings
permalink: none
